// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Connection;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;
        public struct AuthorityRequest : IEntityCommand
        {
                public System.UInt32 requester;
                public System.Int32 authorityType;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 0;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public AuthorityRequest(
                Entity entity,
                System.UInt32 requester,
                System.Int32 authorityType
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.requester = requester; 
                this.authorityType = authorityType; 
            }
            
            public static void Serialize(AuthorityRequest commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteUIntegerRange(commandData.requester, 32, 0);
                bitStream.WriteIntegerRange(commandData.authorityType, 2, 0);
            }
            
            public static AuthorityRequest Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datarequester = bitStream.ReadUIntegerRange(32, 0);
                var dataauthorityType = bitStream.ReadIntegerRange(2, 0);
        
                return new AuthorityRequest()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    requester = datarequester,
                    authorityType = dataauthorityType
                };   
            }
        }
        public struct AuthorityTransfer : IEntityCommand
        {
                public System.UInt32 newAuthority;
                public System.Boolean accepted;
                public System.Int32 authorityType;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 1;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public AuthorityTransfer(
                Entity entity,
                System.UInt32 newAuthority,
                System.Boolean accepted,
                System.Int32 authorityType
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.newAuthority = newAuthority; 
                this.accepted = accepted; 
                this.authorityType = authorityType; 
            }
            
            public static void Serialize(AuthorityTransfer commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteUIntegerRange(commandData.newAuthority, 32, 0);
                bitStream.WriteBool(commandData.accepted);
                bitStream.WriteIntegerRange(commandData.authorityType, 2, 0);
            }
            
            public static AuthorityTransfer Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datanewAuthority = bitStream.ReadUIntegerRange(32, 0);
                var dataaccepted = bitStream.ReadBool();
                var dataauthorityType = bitStream.ReadIntegerRange(2, 0);
        
                return new AuthorityTransfer()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    newAuthority = datanewAuthority,
                    accepted = dataaccepted,
                    authorityType = dataauthorityType
                };   
            }
        }
        public struct QuerySynced : IEntityCommand
        {
                public System.Boolean liveQuerySynced;
                public System.Boolean globalQuerySynced;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 2;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public QuerySynced(
                Entity entity,
                System.Boolean liveQuerySynced,
                System.Boolean globalQuerySynced
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.liveQuerySynced = liveQuerySynced; 
                this.globalQuerySynced = globalQuerySynced; 
            }
            
            public static void Serialize(QuerySynced commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteBool(commandData.liveQuerySynced);
                bitStream.WriteBool(commandData.globalQuerySynced);
            }
            
            public static QuerySynced Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var dataliveQuerySynced = bitStream.ReadBool();
                var dataglobalQuerySynced = bitStream.ReadBool();
        
                return new QuerySynced()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    liveQuerySynced = dataliveQuerySynced,
                    globalQuerySynced = dataglobalQuerySynced
                };   
            }
        }
        public struct AdoptOrphan : IEntityCommand
        {
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 3;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            
            public static void Serialize(AdoptOrphan commandData, IOutProtocolBitStream bitStream)
            {
            }
            
            public static AdoptOrphan Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
        
                return new AdoptOrphan()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                };   
            }
        }
        public struct PersistenceReady : IEntityCommand
        {
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 4;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            
            public static void Serialize(PersistenceReady commandData, IOutProtocolBitStream bitStream)
            {
            }
            
            public static PersistenceReady Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
        
                return new PersistenceReady()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                };   
            }
        }
        public struct SceneIndexChanged : IEntityCommand
        {
                public System.Int32 sceneIndex;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 5;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public SceneIndexChanged(
                Entity entity,
                System.Int32 sceneIndex
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.sceneIndex = sceneIndex; 
            }
            
            public static void Serialize(SceneIndexChanged commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteIntegerRange(commandData.sceneIndex, 32, -2147483648);
            }
            
            public static SceneIndexChanged Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datasceneIndex = bitStream.ReadIntegerRange(32, -2147483648);
        
                return new SceneIndexChanged()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    sceneIndex = datasceneIndex
                };   
            }
        }
        public struct _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181 : IEntityCommand
        {
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 6;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            
            public static void Serialize(_0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181 commandData, IOutProtocolBitStream bitStream)
            {
            }
            
            public static _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
        
                return new _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                };   
            }
        }
        public struct _e8e7b239dff349e43b0021c76df20a39_4d95e3223b694cc5899ce1acafb6279f : IEntityCommand
        {
                public System.String liquidContents;
                public System.Single fillLevel;
                public System.Single targetFill;
                public System.Single acceptableRange;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 7;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public _e8e7b239dff349e43b0021c76df20a39_4d95e3223b694cc5899ce1acafb6279f(
                Entity entity,
                System.String liquidContents,
                System.Single fillLevel,
                System.Single targetFill,
                System.Single acceptableRange
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.StateAuthorityOnly;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.liquidContents = liquidContents; 
                this.fillLevel = fillLevel; 
                this.targetFill = targetFill; 
                this.acceptableRange = acceptableRange; 
            }
            
            public static void Serialize(_e8e7b239dff349e43b0021c76df20a39_4d95e3223b694cc5899ce1acafb6279f commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteString(commandData.liquidContents);
                bitStream.WriteFloat(commandData.fillLevel, FloatMeta.NoCompression());
                bitStream.WriteFloat(commandData.targetFill, FloatMeta.NoCompression());
                bitStream.WriteFloat(commandData.acceptableRange, FloatMeta.NoCompression());
            }
            
            public static _e8e7b239dff349e43b0021c76df20a39_4d95e3223b694cc5899ce1acafb6279f Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var dataliquidContents = bitStream.ReadString();
                var datafillLevel = bitStream.ReadFloat(FloatMeta.NoCompression());
                var datatargetFill = bitStream.ReadFloat(FloatMeta.NoCompression());
                var dataacceptableRange = bitStream.ReadFloat(FloatMeta.NoCompression());
        
                return new _e8e7b239dff349e43b0021c76df20a39_4d95e3223b694cc5899ce1acafb6279f()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    liquidContents = dataliquidContents,
                    fillLevel = datafillLevel,
                    targetFill = datatargetFill,
                    acceptableRange = dataacceptableRange
                };   
            }
        }

}
