// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0542e96b2fd52ce4db07b87b953de2b0_40b1fd9bec8444d6ada31509b4978c07 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0542e96b2fd52ce4db07b87b953de2b0_662675f58bb8413faa4f0eb77b2a3fc1 : EnumBinding
    {   
        private global::GameManagement.GameManager CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GameManagement.GameManager)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529);
        public override string CoherenceComponentName => "_0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)CastedUnityComponent.currentGameState; }
            set { CastedUnityComponent.currentGameState = (GameManagement.GameStateType)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529)coherenceComponent).currentGameState;

            var simFrame = ((_0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529)coherenceComponent).currentGameStateSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.currentGameState = Value;
            }
            else
            {
                update.currentGameState = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.currentGameStateSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0542e96b2fd52ce4db07b87b953de2b0_7135182174108008529();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0542e96b2fd52ce4db07b87b953de2b0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0542e96b2fd52ce4db07b87b953de2b0>();
        
        private global::GameManagement.GameManager _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["40b1fd9bec8444d6ada31509b4978c07"] = new Binding_0542e96b2fd52ce4db07b87b953de2b0_40b1fd9bec8444d6ada31509b4978c07(),
			["662675f58bb8413faa4f0eb77b2a3fc1"] = new Binding_0542e96b2fd52ce4db07b87b953de2b0_662675f58bb8413faa4f0eb77b2a3fc1(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0542e96b2fd52ce4db07b87b953de2b0()
        {
            bakedCommandBindings.Add("95b745d6f6ab4c5c9fac254cce1e1181", BakeCommandBinding__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181_CommandTarget = (global::GameManagement.GameManager)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"GameManagement.GameManager.CmdRequestStartGame",
            	"()",
            	SendCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181,
            	ReceiveLocalCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181,
            	MessageTarget.StateAuthorityOnly,
            	_0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(command);
        }

        private void ReceiveCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(_0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181 command)
        {
			var target = _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181_CommandTarget;
			target.CmdRequestStartGame();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181 castedCommand:
                    ReceiveCommand__0542e96b2fd52ce4db07b87b953de2b0_95b745d6f6ab4c5c9fac254cce1e1181(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0542e96b2fd52ce4db07b87b953de2b0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0542e96b2fd52ce4db07b87b953de2b0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
