// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_6380a1e0e5aed524ebc2143e629bdf47_7024bfb71b0e4d4d9e72065fce0b962c : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_6380a1e0e5aed524ebc2143e629bdf47_dd48b28ad791485ca56cff3eb8ff5cd8 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_6380a1e0e5aed524ebc2143e629bdf47_019ca25d52fa43b2a9bcc9c0beb6283f : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_6380a1e0e5aed524ebc2143e629bdf47_c4b94ad7b6654d7a9d67a39bd10b1866 : FloatBinding
    {   
        private global::Interactables.WorldInteractable.BeerTapController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.WorldInteractable.BeerTapController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027);
        public override string CoherenceComponentName => "_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.syncedAngle); }
            set { CastedUnityComponent.syncedAngle = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent).syncedAngle;

            var simFrame = ((_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent).syncedAngleSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.syncedAngle = Value;
            }
            else
            {
                update.syncedAngle = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.syncedAngleSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_6380a1e0e5aed524ebc2143e629bdf47_2ec4242701434594ba4468b1e7ff2749 : FloatBinding
    {   
        private global::Interactables.WorldInteractable.BeerTapController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.WorldInteractable.BeerTapController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027);
        public override string CoherenceComponentName => "_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.syncedActive); }
            set { CastedUnityComponent.syncedActive = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent).syncedActive;

            var simFrame = ((_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent).syncedActiveSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.syncedActive = Value;
            }
            else
            {
                update.syncedActive = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.syncedActiveSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _6380a1e0e5aed524ebc2143e629bdf47_2436834872552189027();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_6380a1e0e5aed524ebc2143e629bdf47 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_6380a1e0e5aed524ebc2143e629bdf47>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["7024bfb71b0e4d4d9e72065fce0b962c"] = new Binding_6380a1e0e5aed524ebc2143e629bdf47_7024bfb71b0e4d4d9e72065fce0b962c(),
			["dd48b28ad791485ca56cff3eb8ff5cd8"] = new Binding_6380a1e0e5aed524ebc2143e629bdf47_dd48b28ad791485ca56cff3eb8ff5cd8(),
			["019ca25d52fa43b2a9bcc9c0beb6283f"] = new Binding_6380a1e0e5aed524ebc2143e629bdf47_019ca25d52fa43b2a9bcc9c0beb6283f(),
			["c4b94ad7b6654d7a9d67a39bd10b1866"] = new Binding_6380a1e0e5aed524ebc2143e629bdf47_c4b94ad7b6654d7a9d67a39bd10b1866(),
			["2ec4242701434594ba4468b1e7ff2749"] = new Binding_6380a1e0e5aed524ebc2143e629bdf47_2ec4242701434594ba4468b1e7ff2749(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_6380a1e0e5aed524ebc2143e629bdf47()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_6380a1e0e5aed524ebc2143e629bdf47 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_6380a1e0e5aed524ebc2143e629bdf47>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
