// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_fed64c72c6b3443fb4d214bcd357897b : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_7f3e9b9a6922418696fb4bb3f308cb10 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_0968c79f39a04f5ca3cf54b67a89140b : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_a135f61f318a41bfa0b171a8dca940e5 : BoolBinding
    {   
        private global::Interactables.ItemController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.ItemController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651);
        public override string CoherenceComponentName => "_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isHeld); }
            set { CastedUnityComponent.isHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent).isHeld;

            var simFrame = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent).isHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isHeld = Value;
            }
            else
            {
                update.isHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_2853f730fc6443e78e342bb95deb6ab6 : StringBinding
    {   
        private global::Interactables.ItemController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.ItemController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651);
        public override string CoherenceComponentName => "_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.holderId); }
            set { CastedUnityComponent.holderId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent).holderId;

            var simFrame = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent).holderIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.holderId = Value;
            }
            else
            {
                update.holderId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.holderIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f4c6a95abc4bf5d42b04cf35bf8a81e9_5107660060577107651();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9>();
        
        private global::Interactables.ItemController _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7_CommandTarget;
        private global::Interactables.ItemController _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2_CommandTarget;
        private global::Interactables.ItemController _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["fed64c72c6b3443fb4d214bcd357897b"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_fed64c72c6b3443fb4d214bcd357897b(),
			["7f3e9b9a6922418696fb4bb3f308cb10"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_7f3e9b9a6922418696fb4bb3f308cb10(),
			["0968c79f39a04f5ca3cf54b67a89140b"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_0968c79f39a04f5ca3cf54b67a89140b(),
			["a135f61f318a41bfa0b171a8dca940e5"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_a135f61f318a41bfa0b171a8dca940e5(),
			["2853f730fc6443e78e342bb95deb6ab6"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_2853f730fc6443e78e342bb95deb6ab6(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9()
        {
            bakedCommandBindings.Add("b309d033497c4354837e5e432e09aad7", BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7);
            bakedCommandBindings.Add("7d0019cd243c4334be62556af2b967a2", BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2);
            bakedCommandBindings.Add("ea183fe65c4e40faa6a260208034d65b", BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7_CommandTarget = (global::Interactables.ItemController)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Interactables.ItemController.CmdPickup",
            	"(System.String)",
            	SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7,
            	ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7,
            	MessageTarget.All,
            	_f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.playerId = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.playerId = (System.String)requestArgs.Args[0];

            ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(command);
        }

        private void ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(_f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7 command)
        {
			var target = _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7_CommandTarget;
			target.CmdPickup((System.String)(command.playerId));
        }
        private void BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2_CommandTarget = (global::Interactables.ItemController)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Interactables.ItemController.CmdDrop",
            	"()",
            	SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2,
            	ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2,
            	MessageTarget.All,
            	_f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(command);
        }

        private void ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(_f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2 command)
        {
			var target = _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2_CommandTarget;
			target.CmdDrop();
        }
        private void BakeCommandBinding__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b_CommandTarget = (global::Interactables.ItemController)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Interactables.ItemController.CmdPlace",
            	"(UnityEngine.Vector3)",
            	SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b,
            	ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b,
            	MessageTarget.All,
            	_f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.position = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.position = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(command);
        }

        private void ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(_f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b command)
        {
			var target = _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b_CommandTarget;
			target.CmdPlace((UnityEngine.Vector3)(command.position));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7 castedCommand:
                    ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_b309d033497c4354837e5e432e09aad7(castedCommand);
                    break;
                case _f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2 castedCommand:
                    ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_7d0019cd243c4334be62556af2b967a2(castedCommand);
                    break;
                case _f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b castedCommand:
                    ReceiveCommand__f4c6a95abc4bf5d42b04cf35bf8a81e9_ea183fe65c4e40faa6a260208034d65b(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
