// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_fed64c72c6b3443fb4d214bcd357897b : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_7f3e9b9a6922418696fb4bb3f308cb10 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_0968c79f39a04f5ca3cf54b67a89140b : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_3b6dd85e80264d4fbfcc94415455d0a3 : FloatBinding
    {   
        private global::Interactables.ItemInteractables.Mug.MugController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.ItemInteractables.Mug.MugController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945);
        public override string CoherenceComponentName => "_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.fillLevel); }
            set { CastedUnityComponent.fillLevel = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).fillLevel;

            var simFrame = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).fillLevelSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.fillLevel = Value;
            }
            else
            {
                update.fillLevel = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.fillLevelSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_ba79b01ea24b49e2af81c70b26b1c4e6 : BoolBinding
    {   
        private global::Interactables.ItemInteractables.Mug.MugController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.ItemInteractables.Mug.MugController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945);
        public override string CoherenceComponentName => "_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isHeld); }
            set { CastedUnityComponent.isHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).isHeld;

            var simFrame = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).isHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isHeld = Value;
            }
            else
            {
                update.isHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_be12078dc3d14819ac4f28dd24d19d69 : StringBinding
    {   
        private global::Interactables.ItemInteractables.Mug.MugController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Interactables.ItemInteractables.Mug.MugController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945);
        public override string CoherenceComponentName => "_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.holderId); }
            set { CastedUnityComponent.holderId = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).holderId;

            var simFrame = ((_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent).holderIdSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.holderId = Value;
            }
            else
            {
                update.holderId = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.holderIdSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _f4c6a95abc4bf5d42b04cf35bf8a81e9_4491590370692874945();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["fed64c72c6b3443fb4d214bcd357897b"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_fed64c72c6b3443fb4d214bcd357897b(),
			["7f3e9b9a6922418696fb4bb3f308cb10"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_7f3e9b9a6922418696fb4bb3f308cb10(),
			["0968c79f39a04f5ca3cf54b67a89140b"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_0968c79f39a04f5ca3cf54b67a89140b(),
			["3b6dd85e80264d4fbfcc94415455d0a3"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_3b6dd85e80264d4fbfcc94415455d0a3(),
			["ba79b01ea24b49e2af81c70b26b1c4e6"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_ba79b01ea24b49e2af81c70b26b1c4e6(),
			["be12078dc3d14819ac4f28dd24d19d69"] = new Binding_f4c6a95abc4bf5d42b04cf35bf8a81e9_be12078dc3d14819ac4f28dd24d19d69(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_f4c6a95abc4bf5d42b04cf35bf8a81e9>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
