// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Connection;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;
        public struct AuthorityRequest : IEntityCommand
        {
                public System.UInt32 requester;
                public System.Int32 authorityType;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 0;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public AuthorityRequest(
                Entity entity,
                System.UInt32 requester,
                System.Int32 authorityType
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.requester = requester; 
                this.authorityType = authorityType; 
            }
            
            public static void Serialize(AuthorityRequest commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteUIntegerRange(commandData.requester, 32, 0);
                bitStream.WriteIntegerRange(commandData.authorityType, 2, 0);
            }
            
            public static AuthorityRequest Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datarequester = bitStream.ReadUIntegerRange(32, 0);
                var dataauthorityType = bitStream.ReadIntegerRange(2, 0);
        
                return new AuthorityRequest()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    requester = datarequester,
                    authorityType = dataauthorityType
                };   
            }
        }
        public struct AuthorityTransfer : IEntityCommand
        {
                public System.UInt32 newAuthority;
                public System.Boolean accepted;
                public System.Int32 authorityType;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 1;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public AuthorityTransfer(
                Entity entity,
                System.UInt32 newAuthority,
                System.Boolean accepted,
                System.Int32 authorityType
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.newAuthority = newAuthority; 
                this.accepted = accepted; 
                this.authorityType = authorityType; 
            }
            
            public static void Serialize(AuthorityTransfer commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteUIntegerRange(commandData.newAuthority, 32, 0);
                bitStream.WriteBool(commandData.accepted);
                bitStream.WriteIntegerRange(commandData.authorityType, 2, 0);
            }
            
            public static AuthorityTransfer Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datanewAuthority = bitStream.ReadUIntegerRange(32, 0);
                var dataaccepted = bitStream.ReadBool();
                var dataauthorityType = bitStream.ReadIntegerRange(2, 0);
        
                return new AuthorityTransfer()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    newAuthority = datanewAuthority,
                    accepted = dataaccepted,
                    authorityType = dataauthorityType
                };   
            }
        }
        public struct QuerySynced : IEntityCommand
        {
                public System.Boolean liveQuerySynced;
                public System.Boolean globalQuerySynced;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 2;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public QuerySynced(
                Entity entity,
                System.Boolean liveQuerySynced,
                System.Boolean globalQuerySynced
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.liveQuerySynced = liveQuerySynced; 
                this.globalQuerySynced = globalQuerySynced; 
            }
            
            public static void Serialize(QuerySynced commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteBool(commandData.liveQuerySynced);
                bitStream.WriteBool(commandData.globalQuerySynced);
            }
            
            public static QuerySynced Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var dataliveQuerySynced = bitStream.ReadBool();
                var dataglobalQuerySynced = bitStream.ReadBool();
        
                return new QuerySynced()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    liveQuerySynced = dataliveQuerySynced,
                    globalQuerySynced = dataglobalQuerySynced
                };   
            }
        }
        public struct AdoptOrphan : IEntityCommand
        {
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 3;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            
            public static void Serialize(AdoptOrphan commandData, IOutProtocolBitStream bitStream)
            {
            }
            
            public static AdoptOrphan Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
        
                return new AdoptOrphan()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                };   
            }
        }
        public struct PersistenceReady : IEntityCommand
        {
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 4;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            
            public static void Serialize(PersistenceReady commandData, IOutProtocolBitStream bitStream)
            {
            }
            
            public static PersistenceReady Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
        
                return new PersistenceReady()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                };   
            }
        }
        public struct SceneIndexChanged : IEntityCommand
        {
                public System.Int32 sceneIndex;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 5;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public SceneIndexChanged(
                Entity entity,
                System.Int32 sceneIndex
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.sceneIndex = sceneIndex; 
            }
            
            public static void Serialize(SceneIndexChanged commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteIntegerRange(commandData.sceneIndex, 32, -2147483648);
            }
            
            public static SceneIndexChanged Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var datasceneIndex = bitStream.ReadIntegerRange(32, -2147483648);
        
                return new SceneIndexChanged()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    sceneIndex = datasceneIndex
                };   
            }
        }
        public struct EntityRefsCommand : IEntityCommand
        {
                public Entity entityRef1;
                public Entity entityRef2;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 10;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                err = mapper.MapToAbsoluteEntity(entityRef1, false, out absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                this.entityRef1 = absoluteEntity;
                
                err = mapper.MapToAbsoluteEntity(entityRef2, false, out absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                this.entityRef2 = absoluteEntity;
                
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                err = mapper.MapToRelativeEntity(entityRef1, false, out relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                this.entityRef1 = relativeEntity;
                
                err = mapper.MapToRelativeEntity(entityRef2, false, out relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                this.entityRef2 = relativeEntity;
                
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return new HashSet<Entity> {
                    this.entityRef1,
                    this.entityRef2,
                };
            }
    
            public void NullEntityRefs(Entity entity) {
                if (this.entityRef1 == entity) {
                    this.entityRef1 = Entity.InvalidRelative;
                }
                if (this.entityRef2 == entity) {
                    this.entityRef2 = Entity.InvalidRelative;
                }
            }
            
            public EntityRefsCommand(
                Entity entity,
                Entity entityRef1,
                Entity entityRef2
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.entityRef1 = entityRef1; 
                this.entityRef2 = entityRef2; 
            }
            
            public static void Serialize(EntityRefsCommand commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteEntity(commandData.entityRef1);
                bitStream.WriteEntity(commandData.entityRef2);
            }
            
            public static EntityRefsCommand Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var dataentityRef1 = bitStream.ReadEntity();
                var dataentityRef2 = bitStream.ReadEntity();
        
                return new EntityRefsCommand()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    entityRef1 = dataentityRef1,
                    entityRef2 = dataentityRef2
                };   
            }
        }
        public struct ByteArraysCommand : IEntityCommand
        {
                public System.Byte[] bytes1;
                public System.Byte[] bytes2;
                public System.Byte[] bytes3;
                public System.Byte[] bytes4;
                public System.Byte[] bytes5;
                public System.Byte[] bytes6;
            
            public Entity Entity { get; set; }
            public Coherence.ChannelID ChannelID { get; set; }
            public MessageTarget Target { get; set; }
            public MessageTarget Routing { get; set; }
            public uint SenderParticipant { get; set; }
            public ClientID SenderClientID { get; set; }
            public long Frame { get; set; }
            public uint GetComponentType() => 11;
            
            public bool UsesMeta { get; set; }
            
            public IEntityMessage Clone()
            {
                // This is a struct, so we can safely return
                // a struct copy.
                return this;
            }
            
            public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = absoluteEntity;
                return IEntityMapper.Error.None;
            }
            
            public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
            {
                var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
                if (err != IEntityMapper.Error.None)
                {
                    return err;
                }
                Entity = relativeEntity;
                return IEntityMapper.Error.None;
            }
    
            public HashSet<Entity> GetEntityRefs() {
                return default;
            }
    
            public void NullEntityRefs(Entity entity) {
            }
            
            public ByteArraysCommand(
                Entity entity,
                System.Byte[] bytes1,
                System.Byte[] bytes2,
                System.Byte[] bytes3,
                System.Byte[] bytes4,
                System.Byte[] bytes5,
                System.Byte[] bytes6
            )
            {
                Entity = entity;
                ChannelID = Coherence.ChannelID.Default;
                Target = default;
                Routing = MessageTarget.All;
                SenderParticipant = 0;
                SenderClientID = default;
                Frame = 0;
                UsesMeta = false;
                
                this.bytes1 = bytes1; 
                this.bytes2 = bytes2; 
                this.bytes3 = bytes3; 
                this.bytes4 = bytes4; 
                this.bytes5 = bytes5; 
                this.bytes6 = bytes6; 
            }
            
            public static void Serialize(ByteArraysCommand commandData, IOutProtocolBitStream bitStream)
            {
                bitStream.WriteBytes(commandData.bytes1);
                bitStream.WriteBytes(commandData.bytes2);
                bitStream.WriteBytes(commandData.bytes3);
                bitStream.WriteBytes(commandData.bytes4);
                bitStream.WriteBytes(commandData.bytes5);
                bitStream.WriteBytes(commandData.bytes6);
            }
            
            public static ByteArraysCommand Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
            {
                var databytes1 = bitStream.ReadBytes();
                var databytes2 = bitStream.ReadBytes();
                var databytes3 = bitStream.ReadBytes();
                var databytes4 = bitStream.ReadBytes();
                var databytes5 = bitStream.ReadBytes();
                var databytes6 = bitStream.ReadBytes();
        
                return new ByteArraysCommand()
                {
                    Entity = entity,
                    Routing = target,
                    Target = target,
                    bytes1 = databytes1,
                    bytes2 = databytes2,
                    bytes3 = databytes3,
                    bytes4 = databytes4,
                    bytes5 = databytes5,
                    bytes6 = databytes6
                };   
            }
        }

}
